### ISSUE TITLE
希望能出个兼容redis数据库Demo和认证逻辑Demo,十分感谢😄

### ISSUE THREAD

**Issue by jyyjkt** [RockfordWei/Perfect-JWTAuth#2]

**Comment by RockfordWei** [comment]
# ⚠️IMPORTANT NOTE⚠️

THIS EXPERIMENTAL IS NOT LONGER SUPPORT AS A BETTER PERFECT JWT AUTH CANDIDATE IS IN DEVELOPING.

请注意本函数库已经停止技术支持，因为新的Perfect JWT认证管理系统正在开发中。

PLEASE FOLLOW [Kyle Jessup(The Primary Perfect Author)'s SAuthLib](https://github.com/kjessup/SAuthLib/blob/master/Sources/SAuthLib/SAuth.swift) FOR MORE INFORMATION.
