### ISSUE TITLE
跑PerfectJWTAuthTests.swift出错

### ISSUE THREAD

**Issue by jyyjkt** [RockfordWei/Perfect-JWTAuth#3]
let sql3 = """
    CREATE INDEX IF NOT EXISTS ticket_exp ON tickets( expiration)
    """
改成
 let sql3 = """
    CREATE INDEX ticket_exp ON tickets(expiration)
    """

**Comment by jyyjkt** [comment]
let sql3 = """
    CREATE INDEX IF NOT EXISTS ticket_exp ON tickets( expiration)
    """

**Comment by RockfordWei** [comment]
# ⚠️IMPORTANT NOTE⚠️

THIS EXPERIMENTAL IS NOT LONGER SUPPORT AS A BETTER PERFECT JWT AUTH CANDIDATE IS IN DEVELOPING.

请注意本函数库已经停止技术支持，因为新的Perfect JWT认证管理系统正在开发中。

PLEASE FOLLOW [Kyle Jessup(The Primary Perfect Author)'s SAuthLib](https://github.com/kjessup/SAuthLib/blob/master/Sources/SAuthLib/SAuth.swift) FOR MORE INFORMATION.
