### ISSUE TITLE
'HTTPAccessControl<Profile>.Configuration' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by jyyjkt** [RockfordWei/Perfect-JWTAuth#4]

**Comment by jyyjkt** [comment]
//MARK: 封装使PerfectHTTP 2.1过滤器支持
    public static func filterJWTRequest(data: [String:Any]) throws -> HTTPResponseFilter {
        
        let log = FileLogger("/tmp", GMT: true) //打log
        let man = LoginManager<User>(udb: udb!, log: log)
        // 配置一下http服务器，后面会讲配置细节
        let conf = HTTPAccessControl<Profile>.Configuration()
        
        // 用这个配置方案和登录管理器启动http安全认证模块
        let acs = HTTPAccessControl<Profile>(man, configuration: conf)
        
        return acs
    }

**Comment by jyyjkt** [comment]
@testable import PerfectJWTAuth
只能单元测试呢

**Comment by RockfordWei** [comment]
# ⚠️IMPORTANT NOTE⚠️

THIS EXPERIMENTAL IS NOT LONGER SUPPORT AS A BETTER PERFECT JWT AUTH CANDIDATE IS IN DEVELOPING.

请注意本函数库已经停止技术支持，因为新的Perfect JWT认证管理系统正在开发中。

PLEASE FOLLOW [Kyle Jessup(The Primary Perfect Author)'s SAuthLib](https://github.com/kjessup/SAuthLib/blob/master/Sources/SAuthLib/SAuth.swift) FOR MORE INFORMATION.
