### ISSUE TITLE
JWT 这个我多个手机登录会创建多个jwt  只要这些jwt我就不能放到黑名单中  只要像这些同密码同账号的 jwt在没失效前 都能登录 我应该怎样做

### ISSUE THREAD

**Issue by jyyjkt** [RockfordWei/Perfect-JWTAuth#5]

**Comment by RockfordWei** [comment]
# ⚠️IMPORTANT NOTE⚠️

THIS EXPERIMENTAL IS NOT LONGER SUPPORT AS A BETTER PERFECT JWT AUTH CANDIDATE IS IN DEVELOPING.

请注意本函数库已经停止技术支持，因为新的Perfect JWT认证管理系统正在开发中。

PLEASE FOLLOW [Kyle Jessup(The Primary Perfect Author)'s SAuthLib](https://github.com/kjessup/SAuthLib/blob/master/Sources/SAuthLib/SAuth.swift) FOR MORE INFORMATION.
