### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by turkeyaa** [RockfordWei/Perfect-JWTAuth#6]
Xcode 9.4 中编译失败
错误信息："header '/usr/local/include/mariadb/mysql.h' not found"

**Comment by RockfordWei** [comment]
# ⚠️IMPORTANT NOTE⚠️

THIS EXPERIMENTAL IS NOT LONGER SUPPORT AS A BETTER PERFECT JWT AUTH CANDIDATE IS IN DEVELOPING.

请注意本函数库已经停止技术支持，因为新的Perfect JWT认证管理系统正在开发中。

PLEASE FOLLOW [Kyle Jessup(The Primary Perfect Author)'s SAuthLib](https://github.com/kjessup/SAuthLib/blob/master/Sources/SAuthLib/SAuth.swift) FOR MORE INFORMATION.
